##
# Copyright (c) The Nambu Network Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

##
# This configuration file is loaded from initializers/config.rb, and sets a number of configuration items that you will want to 
# change if you are not working on tr.im, but your down installation of a tr.im instance on your own domain name.
#
# Do not forget about /etc/trim.yml as well, outlined in initializers/config.rb.
##

website_id: 1
website_url: http://tr.im/
website_domain: tr.im
website_blog_url: http://blog.tr.im/
website_blog_feed: feed://blog.tr.im/rss

href_width_account: 52
href_width_homepage: 60
urlslist_width_account: 650
urlslist_width_homepage: 935

max_search_results: 50

inline_width_default: 350
inline_width_iphone: 555
inline_width_maximum: 825

chart_countries_per_pie: 6
chart_referers_per_pie: 4
chart_timeline_width: 835
chart_agents_width: 420
chart_height_clicks: 200
chart_height_countries: 200
chart_height_countries_higher: 320

firefox_url: https://addons.mozilla.org/en-US/firefox/addon/10232/
ubiquity_url: http://tr.im/scripts/trimUbiquity

dashboard_url: http://tr.im/download/dashboard/
dashboard_trimit_url: http://www.apple.com/downloads/dashboard/blogs_forums/trimit.html
